[versions]
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
jacoco = "0.8.10"
uiautomator = "2.2.0"
benchmark-macro-junit4 = "1.2.0-beta01"
rules = "1.5.0"
tracing-ktx = "1.3.0-alpha02"
tracing-compose = "1.0.0-beta01"
tracing-perfetto = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# For benchmark
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "tracing-ktx" }
androidx-compose-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "tracing-compose" }
androidx-tracing-perfettor = { group = "androidx.tracing", name = "tracing-perfetto", version.ref = "tracing-perfetto" }
androidx-tracing-perfettor-binary = { group = "androidx.tracing", name = "tracing-perfetto-binary", version.ref = "tracing-perfetto" }
